import assert from "node:assert/strict";
import { mkdir, readFile, writeFile, mkdtemp } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import test from "node:test";
import { checkContractFiles, computeLayoutContractIdentityHash, main, validateContract } from "./validate_ui_layout_contract.mjs";

const templatePath = resolve(dirname(new URL(import.meta.url).pathname.replace(/^\/(.:)/, "$1")), "../assets/ui-layout-contract-template.yaml");
const base = JSON.parse(await readFile(templatePath, "utf8"));

/** 深拷贝基准合同，避免测试之间共享修改。 */
function copy() { return structuredClone(base); }
/** 构造冻结目标的 specified 或 verified 布局合同。 */
function fidelityContract(status = "verified") {
  const document = copy(); const targetSha = `sha256:${"1".repeat(64)}`; const candidateSha = document.scope.bindings.code_candidate;
  document.fidelity = { applicability: "frozen-target", status }; document.effect_image_reconstruction = { applicability: "effect-image" };
  document.frozen_visual_target = { candidate_id: "mockup-a", original_file: "evidence/target.png", target_sha256: targetSha, visual_baseline_version: "ui-v1", status: "frozen" };
  document.scene_reconstruction_binding = { target_sha256: targetSha, scene_id: "MainScene", state_id: "default", visual_baseline_version: "ui-v1", reconstruction_contract_version: "1.0.0", layout_contract_sha256: "pending", layout_decomposition_version: "layout-v1", target_viewport: { width: 390, height: 844 } };
  document.layout_nodes = [{ layout_node_id: "hud.title", region_id: "title", coordinate_space: "ui-space", reference_id: "safe-area", parent_layout_node_id: "safe-area", parent_target_bounds: { x: 0, y: 0, width: 390, height: 844 }, relative_position: { left: 115, right: 115, top: 32, bottom: 764 }, axis_alignment: { horizontal: "center", vertical: "top" }, self_anchor: "top-center", reference_anchor: "top-center", offset: { x: 0, y: 32 }, target_bounds: { x: 115, y: 32, width: 160, height: 48 }, size_policy: "fixed-at-target", z_order: 10, clip_policy: "none", responsive_rule: "preserve-center-and-top-gap", planned_test_id: "tests/layout/title-center" }];
  document.layout_annotation = { layout_annotation_file: "evidence/layout-annotation.png", layout_annotation_sha256: targetSha, layout_annotation_width: 390, layout_annotation_height: 844, layout_annotation_schema: "layout-annotation/png/1", layout_annotation_layout: "image-plus-right-panel", layout_annotation_metadata_sha256: targetSha, layout_annotation_identity_sha256: targetSha, decomposition_confirmation_id: "v2-confirmation", decomposition_confirmation_sha256: targetSha, proposal_sha256: targetSha, layout_decision_file: "evidence/automatic-layout-decision.json", layout_decision_sha256: targetSha, layout_decision_id: "layout-decision-1", target_sha256: targetSha, scene_id: "MainScene", state_id: "default", layout_node_ids: ["hud.title"] };
  document.scene_reconstruction_binding.layout_contract_sha256 = computeLayoutContractIdentityHash(document);
  document.critical_alignments = [{ id: "title-center", layout_node_id: "hud.title", element_id: "title", reference_id: "safe-area", horizontal: { type: "center-aligned", element_anchor: "center", reference_anchor: "center" }, vertical: { type: "top-offset", element_anchor: "top", reference_anchor: "top" }, target_measurement: { x: 115, y: 32, width: 160, height: 48 }, planned_test_id: "tests/layout/title-center", target_evidence: ["evidence/target-title.png"], target_sha256: targetSha, candidate_sha256: candidateSha, tolerance: { unit: "logical-px", value: 2 } }];
  if (status === "verified") { Object.assign(document.critical_alignments[0], { actual_test_id: "tests/layout/title-center", runtime_measurement: { x: 115, y: 32, width: 160, height: 48 }, delta: { x: 0, y: 0, width: 0, height: 0 }, test_status: "passed", runtime_evidence: ["evidence/runtime-title.png"] }); document.parity_cases = [{ id: "main-default", target_sha256: targetSha, candidate_sha256: candidateSha, scene_id: "MainScene", state_id: "default", viewport: { width: 390, height: 844 }, dpr: 1.5, language: "zh-CN", random_seed: 42, input_trace: "traces/main.json", sample_rule: "stable-frame", layout_contract_version: "1.0.0", visual_baseline_version: "ui-v1", reference_evidence: ["evidence/target.png"], candidate_evidence: ["evidence/candidate.png"], tolerance: { unit: "logical-px", value: 2 }, exception_ids: [], conclusion: "passed" }]; }
  return document;
}
/** 断言指定缺陷稳定地产生失败和可定位诊断。 */
function assertFailed(document, expected) { const result = validateContract(document); assert.equal(result.status, "failed"); assert(result.errors.some((item) => item.includes(expected)), JSON.stringify(result)); }

test("普通布局合同通过且保留专项标记", () => { const result = validateContract(copy()); assert.equal(result.status, "passed", JSON.stringify(result)); assert(result.specialized_review.includes("primary-action:docked-overlay")); });
test("specified 冻结目标合同允许尚无运行测量和 parity", () => { const result = validateContract(fidelityContract("specified")); assert.equal(result.status, "passed", JSON.stringify(result)); });
test("frozen-target 缺少 scene_reconstruction_binding 必须失败，普通布局无需绑定", () => { const frozen = fidelityContract("specified"); delete frozen.scene_reconstruction_binding; assertFailed(frozen, "scene_reconstruction_binding 缺失"); const ordinary = copy(); delete ordinary.scene_reconstruction_binding; assert.equal(validateContract(ordinary).status, "passed"); });
test("actual_test_id 仅在 verified 必需", () => { const document = fidelityContract(); delete document.critical_alignments[0].actual_test_id; assertFailed(document, "actual_test_id 必须"); });
test("verified 身份必须与 scope、合同和基线一致", () => { const scene = fidelityContract(); scene.parity_cases[0].scene_id = "Unknown"; assertFailed(scene, "scene_id 不在 scope"); const layout = fidelityContract(); layout.parity_cases[0].layout_contract_version = "9"; assertFailed(layout, "根 contract_version 不一致"); const baseline = fidelityContract(); baseline.parity_cases[0].visual_baseline_version = "other"; assertFailed(baseline, "与冻结目标不一致"); const testId = fidelityContract(); testId.critical_alignments[0].actual_test_id = "other-test"; assertFailed(testId, "必须等于 planned_test_id"); });
test("关键对齐缺关系或 verified 缺运行测量失败", () => { const relation = fidelityContract("specified"); delete relation.critical_alignments[0].horizontal; assertFailed(relation, "horizontal 缺少关系"); const measurement = fidelityContract(); delete measurement.critical_alignments[0].runtime_measurement; assertFailed(measurement, "runtime_measurement 必须包含数值"); });
test("关键对齐未知 UI ID 与未执行测试失败", () => { const unknown = fidelityContract(); unknown.critical_alignments[0].element_id = "unknown-ui"; assertFailed(unknown, "element_id 引用未知 UI ID"); const untested = fidelityContract(); untested.critical_alignments[0].test_status = "not-run"; assertFailed(untested, "未执行测试不得通过"); });
test("关键对齐目标和候选 SHA 必须匹配", () => { for (const field of ["target_sha256", "candidate_sha256"]) { const document = fidelityContract(); document.critical_alignments[0][field] = `sha256:${"f".repeat(64)}`; assertFailed(document, field === "target_sha256" ? "与冻结目标不一致" : "与当前代码候选不一致"); } });
test("effect-image 布局节点必须完整绑定区域、坐标空间和目标视口", () => { const document = fidelityContract("specified"); assert.equal(validateContract(document).status, "passed"); const missing = fidelityContract("specified"); delete missing.layout_nodes[0].coordinate_space; assertFailed(missing, "coordinate_space 必须是非空字符串"); const orphan = fidelityContract("specified"); orphan.layout_nodes[0].region_id = "orphan-region"; assertFailed(orphan, "孤立布局节点"); const outOfBounds = fidelityContract("specified"); outOfBounds.layout_nodes[0].target_bounds.x = 300; assertFailed(outOfBounds, "target_bounds 必须完全位于"); });
test("effect-image 父子布局字段缺失或伪造必须失败", () => { for (const mutate of [node => delete node.parent_layout_node_id, node => { node.reference_id = "viewport"; }, node => { node.relative_position.left += 1; }, node => { node.axis_alignment.horizontal = "right"; }, node => { node.offset.x = 999; }, node => { node.self_anchor = "center-center"; }]) { const document = fidelityContract("specified"); mutate(document.layout_nodes[0]); assert.equal(validateContract(document).status, "failed"); } });
test("同一 coverage region 可以绑定多个布局节点，且多节点区域参照必须具体化", () => { const sameRegion = fidelityContract("specified"); sameRegion.layout_nodes.push({ ...structuredClone(sameRegion.layout_nodes[0]), layout_node_id: "hud.title-decoration", reference_id: "hud.title", parent_layout_node_id: "hud.title", parent_target_bounds: { x: 115, y: 32, width: 160, height: 48 }, relative_position: { left: 0, right: 0, top: 0, bottom: 0 }, axis_alignment: { horizontal: "center", vertical: "center" }, self_anchor: "center-center", reference_anchor: "center-center", offset: { x: 0, y: 0 } }); sameRegion.layout_annotation.layout_node_ids.push("hud.title-decoration"); sameRegion.scene_reconstruction_binding.layout_contract_sha256 = computeLayoutContractIdentityHash(sameRegion); assert.equal(validateContract(sameRegion).status, "passed"); const ambiguousReference = structuredClone(sameRegion); ambiguousReference.layout_nodes[0].reference_id = "title"; assertFailed(ambiguousReference, "包含多个 layout_nodes 的 region"); const ambiguousAlignment = structuredClone(sameRegion); ambiguousAlignment.critical_alignments[0].reference_id = "title"; assertFailed(ambiguousAlignment, "包含多个 layout_nodes 的 region"); });
test("布局节点 ID 和稳定参照必须唯一且无环", () => { const duplicateNode = fidelityContract("specified"); duplicateNode.layout_nodes.push(structuredClone(duplicateNode.layout_nodes[0])); assertFailed(duplicateNode, "重复布局节点 ID"); const badReference = fidelityContract("specified"); badReference.layout_nodes[0].reference_id = "missing-reference"; assertFailed(badReference, "不存在的稳定参照"); const cycle = fidelityContract("specified"); cycle.layout_nodes.push({ ...structuredClone(cycle.layout_nodes[0]), layout_node_id: "hud.other", region_id: "content-panel", reference_id: "hud.title" }); cycle.layout_nodes[0].reference_id = "hud.other"; cycle.scene_reconstruction_binding.layout_contract_sha256 = computeLayoutContractIdentityHash(cycle); assertFailed(cycle, "布局节点参照存在循环"); });
test("关键对齐必须绑定节点几何，禁止目标漂移", () => { const document = fidelityContract("specified"); document.critical_alignments[0].target_measurement.x += 1; assertFailed(document, "目标几何漂移"); const missingNode = fidelityContract("specified"); missingNode.critical_alignments[0].layout_node_id = "missing-node"; assertFailed(missingNode, "引用未知布局节点"); });
test("布局合同身份哈希包含节点原顺序并拒绝节点篡改后的旧身份", () => { const document = fidelityContract("specified"); assert.equal(document.scene_reconstruction_binding.layout_contract_sha256, computeLayoutContractIdentityHash(document)); const second = { ...structuredClone(document.layout_nodes[0]), layout_node_id: "hud.second", reference_id: "hud.title", parent_layout_node_id: "hud.title", parent_target_bounds: { x: 115, y: 32, width: 160, height: 48 }, relative_position: { left: 0, right: 0, top: 0, bottom: 0 }, axis_alignment: { horizontal: "center", vertical: "center" }, self_anchor: "center-center", reference_anchor: "center-center", offset: { x: 0, y: 0 } }; const ordered = structuredClone(document); ordered.layout_nodes.push(second); const reordered = structuredClone(ordered); reordered.layout_nodes.reverse(); assert.notEqual(computeLayoutContractIdentityHash(reordered), computeLayoutContractIdentityHash(ordered)); const tampered = fidelityContract("specified"); tampered.layout_nodes[0].target_bounds.x += 1; assertFailed(tampered, "布局合同身份不一致"); });
test("布局合同身份哈希包含父子关系、相对距离和视觉对齐字段", () => { const document = fidelityContract("specified"); const identity = document.scene_reconstruction_binding.layout_contract_sha256; for (const field of ["parent_layout_node_id", "parent_target_bounds", "relative_position", "axis_alignment"]) { const tampered = fidelityContract("specified"); if (field === "parent_layout_node_id") tampered.layout_nodes[0][field] = "viewport"; else if (field === "parent_target_bounds") tampered.layout_nodes[0][field].width -= 1; else if (field === "relative_position") tampered.layout_nodes[0][field].left += 1; else tampered.layout_nodes[0][field].horizontal = "right"; assert.notEqual(computeLayoutContractIdentityHash(tampered), identity, field); } });
test("verified 关键对齐必须记录实际 bounds、delta 和运行证据", () => { const missingDelta = fidelityContract(); delete missingDelta.critical_alignments[0].delta; assertFailed(missingDelta, "delta 必须"); const wrongDelta = fidelityContract(); wrongDelta.critical_alignments[0].delta.x = 1; assertFailed(wrongDelta, "必须等于 runtime_measurement"); const missingBindingIdentity = fidelityContract("specified"); delete missingBindingIdentity.scene_reconstruction_binding.layout_contract_sha256; assertFailed(missingBindingIdentity, "layout_contract_sha256 必须"); });
test("目标和代码候选 SHA 格式固定", () => { const code = copy(); code.scope.bindings.code_candidate = "git:abc"; assertFailed(code, "code_candidate 必须是 sha256"); const target = fidelityContract("specified"); target.frozen_visual_target.target_sha256 = "sha256:BAD"; assertFailed(target, "target_sha256 格式无效"); });
test("verified parity 必须全部通过且身份完整", () => { const target = fidelityContract(); target.parity_cases[0].target_sha256 = `sha256:${"e".repeat(64)}`; assertFailed(target, "与冻结目标不一致"); const failed = fidelityContract(); failed.parity_cases[0].conclusion = "failed"; assertFailed(failed, "必须全部 passed"); const evidence = fidelityContract(); evidence.parity_cases[0].candidate_evidence = []; assertFailed(evidence, "candidate_evidence 必须是非空字符串数组"); });
test("布局 parity DPR 允许动态有效值并拒绝越界或隐式值", () => {
  for (const dpr of [0.5, 1, 1.25, 1.5]) { const document = fidelityContract(); document.parity_cases[0].dpr = dpr; assert.equal(validateContract(document).status, "passed", `dpr=${dpr}`); }
  for (const dpr of [0, -1, 1.5001, 2, 3, "1.5", NaN, Infinity]) { const document = fidelityContract(); document.parity_cases[0].dpr = dpr; assertFailed(document, "必须是正有限数字且不超过 1.5"); }
});
test("布局 targets.scale 使用动态封顶策略并保留生产上限", () => {
  const invalidPolicy = copy(); invalidPolicy.targets.scale.dpr_policy = "fixed-2"; assertFailed(invalidPolicy, "dpr_policy 必须为 dynamic-capped-1.5");
  const invalidMax = copy(); invalidMax.targets.scale.max_dpr = 2; assertFailed(invalidMax, "max_dpr 必须严格为 1.5");
  const legacyDpr = copy(); legacyDpr.targets.scale.dpr = 2; assertFailed(legacyDpr, "targets.scale.dpr 必须是正有限数字且不超过 1.5");
  const valid = copy(); valid.targets.scale.dpr = 1.5; assert.equal(validateContract(valid).status, "passed");
});
test("布局 evidence matrix 扩展 case 的 DPR 允许有效值但拒绝非法值", () => {
  const valid = copy(); valid.evidence_matrix.cases = [{ dpr: 1 }, { deviceScaleFactor: 1.5 }]; assert.equal(validateContract(valid).status, "passed");
  const invalid = copy(); invalid.evidence_matrix.cases = [{ dpr: 0 }, { deviceScaleFactor: "2" }]; assertFailed(invalid, "evidence_matrix");
});
test("关键对齐与 parity ID 必须唯一", () => { const alignment = fidelityContract(); alignment.critical_alignments.push(structuredClone(alignment.critical_alignments[0])); assertFailed(alignment, "id 重复"); const parity = fidelityContract(); parity.parity_cases.push(structuredClone(parity.parity_cases[0])); assertFailed(parity, "id 重复"); });
test("缺少坐标空间失败", () => { const document = copy(); document.coordinate_spaces = []; assertFailed(document, "coordinate_spaces 必须是非空数组"); });
test("坐标空间循环失败", () => { const document = copy(); document.coordinate_spaces[0].parent = "ui-space"; document.coordinate_spaces[1].parent = "screen-space"; assertFailed(document, "坐标空间存在循环"); });
test("范围区域 ID 必须一致", () => { const document = copy(); document.scope.ui_ids.splice(document.scope.ui_ids.indexOf("title"), 1); assertFailed(document, "scope.ui_ids 缺少 regions ID"); });
test("水平和垂直锚点均必需", () => { for (const axis of ["horizontal", "vertical"]) { const document = copy(); delete document.regions[0].anchors[axis]; assertFailed(document, `anchors.${axis} 缺失`); } });
test("不存在的参照失败", () => { const document = copy(); document.regions[1].reference_id = "not-found"; assertFailed(document, "不存在的 reference_id"); });
test("区域参照循环失败", () => { const document = copy(); document.regions[2].reference_id = "content-panel"; document.regions[3].reference_id = "title"; assertFailed(document, "区域参照存在循环"); });
test("缺少和重复滚动所有者失败", () => { const missing = copy(); delete missing.scrolling.axes; assertFailed(missing, "scrolling.axes 必须是数组"); const duplicate = copy(); duplicate.scrolling.axes.push(structuredClone(duplicate.scrolling.axes[0])); assertFailed(duplicate, "滚动轴存在多个所有者"); });
test("普通静态 HUD 允许无断点、滚动轴和关键动作", () => { const document = copy(); document.breakpoints = []; document.scrolling.axes = []; document.dynamic_content.key_actions = []; assert.equal(validateContract(document).status, "passed"); });
test("关键动作禁止截断", () => { const document = copy(); document.dynamic_content.key_actions[0].text_truncation = "allow"; assertFailed(document, "关键动作禁止文本截断"); });
test("覆盖层缺少回退失败", () => { const document = copy(); delete document.overlay_rules[0].fallback; assertFailed(document, "fallback 必须声明回退规则"); });
test("特殊布局缺少覆盖规则失败", () => { const document = copy(); document.regions[5].layout_participation = "fixed-overlay"; assertFailed(document, "fixed-overlay 缺少对应 overlay_rules"); });
test("不变量必须具备两类证据", () => { const document = copy(); document.invariants[0].evidence.visual = []; assertFailed(document, "evidence.visual 必须是非空数组"); });
test("重复 UI ID 失败", () => { const document = copy(); document.scope.ui_ids.push("title"); assertFailed(document, "重复 UI ID"); });
test("证据矩阵缺少必需轴失败", () => { const document = copy(); document.evidence_matrix.required_axes.splice(document.evidence_matrix.required_axes.indexOf("dpr"), 1); assertFailed(document, "required_axes 缺少必需轴"); });
test("无效断点条件失败", () => { const document = copy(); document.breakpoints[0].when = { width_lt: null }; assertFailed(document, "when 必须包含非空键和有效值"); });
test("绝对和固定布局触发专项审查", () => { const document = copy(); document.regions[2].positioning = "absolute"; document.regions[2].size.strategy = "fixed"; const result = validateContract(document); assert.equal(result.status, "passed", JSON.stringify(result)); assert(result.specialized_review.includes("title:absolute-positioning")); assert(result.specialized_review.includes("title:fixed-size")); });
test("CLI 对无效合同返回非零", async () => { const document = copy(); delete document.regions[0].anchors.horizontal; const directory = await mkdtemp(join(tmpdir(), "layout-contract-")); const path = join(directory, "contract.yaml"); await writeFile(path, JSON.stringify(document)); assert.notEqual(await main([path]), 0); });
test("布局文件检查覆盖缺文件、哈希和路径逃逸", async () => { const root = await mkdtemp(join(tmpdir(), "layout-files-")); const document = fidelityContract(); assert((await checkContractFiles(document, root)).some((item) => item.includes("文件不存在"))); const files = ["evidence/target.png", "evidence/layout-annotation.png", "evidence/automatic-layout-decision.json", "evidence/target-title.png", "evidence/runtime-title.png", "evidence/candidate.png"]; for (const value of files) { const path = join(root, value); await mkdir(dirname(path), { recursive: true }); await writeFile(path, ""); } document.frozen_visual_target.target_sha256 = "sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"; document.layout_annotation.layout_annotation_sha256 = document.frozen_visual_target.target_sha256; document.layout_annotation.layout_decision_sha256 = document.frozen_visual_target.target_sha256; assert.deepEqual(await checkContractFiles(document, root), []); await writeFile(join(root, "evidence/target.png"), "changed"); assert((await checkContractFiles(document, root)).some((item) => item.includes("SHA-256 不一致"))); document.critical_alignments[0].target_evidence = ["../escape.png"]; assert((await checkContractFiles(document, root)).some((item) => item.includes("路径逃逸"))); });
