import assert from "node:assert/strict";
import { mkdtemp, mkdir, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import sharp from "sharp";
import { main, parseAtlas } from "./spine_reskin_progress.mjs";

/** 创建指定颜色的 RGBA PNG。 */
async function writeImage(path, width, height, fill = [0, 0, 0, 0], pixels = []) { const data = Buffer.alloc(width * height * 4); for (let index = 0; index < width * height; index += 1) for (let channel = 0; channel < 4; channel += 1) data[index * 4 + channel] = fill[channel]; for (const [x, y, color] of pixels) for (let channel = 0; channel < 4; channel += 1) data[(y * width + x) * 4 + channel] = color[channel]; await sharp(data, { raw: { width, height, channels: 4 } }).png().toFile(path); }
/** 解码 PNG 原始像素。 */
async function readImage(path) { const { data, info } = await sharp(path).ensureAlpha().raw().toBuffer({ resolveWithObject: true }); return { data, width: info.width, pixel(x, y) { return [...data.subarray((y * info.width + x) * 4, (y * info.width + x + 1) * 4)]; } }; }
/** 调用 mark 子命令。 */
async function mark(fixture, cell, status, image, error) { const args = ["mark", "--manifest", fixture.manifest, "--cell", cell, "--status", status]; if (image) args.push("--image", image); if (error) args.push("--error", error); return main(args); }

/** 为每个测试建立隔离 Atlas、源 Page 和候选目录。 */
async function fixture() {
  const root = await mkdtemp(join(tmpdir(), "spine-reskin-")); await writeImage(join(root, "source.png"), 10, 8, [17, 29, 41, 255]); const atlas = join(root, "source.atlas"); await writeFile(atlas, `source.png\nsize: 10, 8\nformat: RGBA8888\nfilter: Linear,Linear\nrepeat: none\npma: false\n\nhero\n  rotate: false\n  xy: 1, 1\n  size: 3, 2\n  orig: 5, 4\n  offset: 1, 1\n  index: -1\n\nrot\n  rotate: true\n  xy: 5, 1\n  size: 2, 3\n  orig: 3, 4\n  offset: 0, 0\n  index: -1\n`); const candidate = join(root, "candidate"); const generated = join(candidate, "generated"); await mkdir(generated, { recursive: true }); const manifest = join(candidate, "progress.json"); assert.equal(await main(["init", "--atlas", atlas, "--output", manifest, "--reference-dir", join(candidate, "source-cells")]), 0); const document = JSON.parse(await readFile(manifest, "utf8")); assert.equal(document.cells.length, 2); await readFile(join(candidate, "source-cells", "p0_hero.png")); return { root, atlas, candidate, generated, manifest };
}

/** 写入未裁剪 hero 和旋转 Cell 生成图。 */
async function writeGenerated(f) { const hero = join(f.generated, "hero.png"); const heroPixels = []; for (let y = 1; y < 3; y += 1) for (let x = 1; x < 4; x += 1) heroPixels.push([x, y, [200, 20 + y, 30 + x, 255]]); await writeImage(hero, 5, 4, [0, 0, 0, 0], heroPixels); const rotated = join(f.generated, "rot.png"); await writeImage(rotated, 3, 4, [0, 0, 0, 0], [[0, 2, [255, 0, 0, 255]], [1, 2, [0, 255, 0, 255]], [2, 2, [0, 0, 255, 255]], [0, 3, [255, 255, 0, 255]], [1, 3, [255, 0, 255, 255]], [2, 3, [0, 255, 255, 255]]]); return [hero, rotated]; }

test("状态恢复、失败重试和未完成验证", async () => { const f = await fixture(); const [hero] = await writeGenerated(f); assert.equal(await mark(f, "p0:hero", "generating"), 0); assert.equal(await main(["recover", "--manifest", f.manifest]), 0); assert.equal(JSON.parse(await readFile(f.manifest, "utf8")).cells[0].status, "pending"); assert.equal(await mark(f, "p0:hero", "failed", null, "生成器超时"), 0); assert.equal(await mark(f, "p0:hero", "generating"), 0); assert.equal(await mark(f, "p0:hero", "generated", hero), 0); assert.equal(await main(["verify", "--manifest", f.manifest]), 1); assert.equal(await main(["status", "--manifest", f.manifest]), 0); });

test("空白页重建保持裁剪、UV 旋转和哈希校验", async () => { const f = await fixture(); const [hero, rotated] = await writeGenerated(f); assert.equal(await mark(f, "p0:hero", "generated", hero), 0); assert.equal(await mark(f, "p0:rot", "generating"), 0); assert.equal(await mark(f, "p0:rot", "generated", rotated), 0); assert.equal(await mark(f, "p0:hero", "validating"), 0); assert.equal(await mark(f, "p0:rot", "validating"), 0); const output = join(f.candidate, "atlas"); assert.equal(await main(["pack", "--manifest", f.manifest, "--output-dir", output]), 0); const image = await readImage(join(output, "source.png")); assert.deepEqual(image.pixel(0, 0), [0, 0, 0, 0]); assert.deepEqual(image.pixel(1, 1), [200, 21, 31, 255]); assert.deepEqual(image.pixel(5, 1), [255, 255, 0, 255]); assert.deepEqual(image.pixel(6, 3), [0, 0, 255, 255]); assert.equal(await main(["verify", "--manifest", f.manifest]), 0); const page = join(output, "source.png"); const bytes = await readFile(page); bytes[bytes.length - 1] ^= 1; await writeFile(page, bytes); assert.equal(await main(["verify", "--manifest", f.manifest]), 1); const atlas = join(output, "source.atlas"); await writeFile(atlas, `${await readFile(atlas, "utf8")}# tampered\n`); assert.equal(await main(["verify", "--manifest", f.manifest]), 1); assert.equal((await parseAtlas(atlas)).cells.length, 2); });

test("padding 与 extrusion 只使用生成像素", async () => { const f = await fixture(); const document = JSON.parse(await readFile(f.manifest, "utf8")); document.cells = [document.cells[0]]; Object.assign(document.cells[0], { name: "padded", id: "p0:padded", xy: [2, 2], size: [4, 4], orig: [4, 4], offset: [0, 0] }); await writeFile(f.manifest, JSON.stringify(document, null, 2)); const core = join(f.generated, "core.png"); await writeImage(core, 2, 2, [90, 40, 10, 255]); assert.equal(await mark(f, "p0:padded", "generated", core), 0); assert.equal(await mark(f, "p0:padded", "validating"), 0); const output = join(f.candidate, "padded-atlas"); assert.equal(await main(["pack", "--manifest", f.manifest, "--output-dir", output, "--padding", "1", "--extrusion", "1"]), 0); const image = await readImage(join(output, "source.png")); for (let x = 2; x < 6; x += 1) for (let y = 2; y < 6; y += 1) assert.deepEqual(image.pixel(x, y), [90, 40, 10, 255]); });

test("PMA 在写入空白页时只预乘一次", async () => { const f = await fixture(); const document = JSON.parse(await readFile(f.manifest, "utf8")); document.cells = [document.cells[0]]; document.atlas.pages[0].fields.pma = "true"; await writeFile(f.manifest, JSON.stringify(document, null, 2)); const hero = join(f.generated, "pma.png"); await writeImage(hero, 5, 4, [0, 0, 0, 0], [[1, 1, [200, 100, 50, 128]]]); assert.equal(await mark(f, "p0:hero", "generated", hero), 0); assert.equal(await mark(f, "p0:hero", "validating"), 0); const output = join(f.candidate, "pma-atlas"); assert.equal(await main(["pack", "--manifest", f.manifest, "--output-dir", output]), 0); const image = await readImage(join(output, "source.png")); assert.deepEqual(image.pixel(1, 1), [100, 50, 25, 128]); assert.deepEqual(image.pixel(0, 0), [0, 0, 0, 0]); });
