import { createHash } from "node:crypto";
import { deriveAtomicImageRequirements, normalizeAtomicComponents } from "../../phaser4-game-workflow-control/scripts/visual-atomic-contract.mjs";
import { annotationProductionContract, renderRasterAnnotation } from "./effect_image_raster.mjs";

/** 标注图使用的固定计划颜色，机器值与展示标签分离，便于审计和人工阅读。 */
export const PLAN_COLORS = { "generate-now": "#ef4444", "reuse-existing": "#22c55e", "runtime-program": "#3b82f6" };
/** 标注图使用的三类中文展示标签。 */
export const PLAN_LABELS = { "generate-now": "本次生成", "reuse-existing": "复用既有资源", "runtime-program": "程序实现" };
// 确认哈希覆盖所有会改变生产合同或拆解粒度的字段；自声明 production_method_changed 不能替代此不可变身份。
const REGION_DEFINITION_FIELDS = ["scene_id", "state_id", "layer", "bounds", "owner_type", "owner_id", "asset_id", "asset_ids", "production_origin", "production_method", "delivery_kind", "image_generation_required", "generation_record_required", "substitution_policy", "runtime_implementation", "state_analysis", "component_inventory", "expected_assets", "interaction_hotspots", "atomic_image_requirements", "ownership_evidence", "annotation_number", "implementation_plan"];

/** 判断值是否为普通 JSON 对象。 */
function isObject(value) { return value !== null && typeof value === "object" && !Array.isArray(value); }
/** 以稳定的键顺序序列化区域定义，避免属性插入顺序影响身份哈希。 */
function canonicalize(value) { if (Array.isArray(value)) return `[${value.map((item) => canonicalize(item)).join(",")}]`; if (isObject(value)) return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${canonicalize(value[key])}`).join(",")}}`; const encoded = JSON.stringify(value); return encoded === undefined ? "null" : encoded; }
const REGION_FIELD_ALIASES = Object.freeze({ scene_id: ["scene_id", "sceneId"], state_id: ["state_id", "stateId"], layer: ["layer"], owner_type: ["owner_type", "ownerType"], owner_id: ["owner_id", "ownerId"], asset_id: ["asset_id", "assetId"], asset_ids: ["asset_ids", "assetIds"], production_origin: ["production_origin", "productionOrigin"], production_method: ["production_method", "productionMethod"], delivery_kind: ["delivery_kind", "deliveryKind"], image_generation_required: ["image_generation_required", "imageGenerationRequired"], generation_record_required: ["generation_record_required", "generationRecordRequired"], substitution_policy: ["substitution_policy", "substitutionPolicy"], runtime_implementation: ["runtime_implementation", "runtimeImplementation"], state_analysis: ["state_analysis", "stateAnalysis"], component_inventory: ["component_inventory", "componentInventory"], expected_assets: ["expected_assets", "expectedAssets"], interaction_hotspots: ["interaction_hotspots", "interactionHotspots"], atomic_image_requirements: ["atomic_image_requirements", "atomicImageRequirements"], ownership_evidence: ["ownership_evidence", "ownershipEvidence"], annotation_number: ["annotation_number", "annotationNumber"], implementation_plan: ["implementation_plan", "implementationPlan"], bounds: ["bounds"] });
const NESTED_CONTRACT_FIELDS = new Set(["production_origin", "production_method", "delivery_kind", "image_generation_required", "generation_record_required", "substitution_policy", "runtime_implementation", "state_analysis", "component_inventory", "expected_assets", "interaction_hotspots", "atomic_image_requirements"]);
const STATE_ALIASES = new Map([["default", "default"], ["normal", "default"], ["idle", "default"], ["selected", "selected"], ["select", "selected"], ["active", "active"], ["activated", "active"], ["disabled", "disabled"], ["disable", "disabled"], ["pressed", "pressed"], ["down", "pressed"], ["hover", "hover"], ["hovered", "hover"], ["over", "hover"], ["victory", "victory"], ["win", "victory"], ["won", "victory"], ["success", "victory"], ["defeat", "defeat"], ["lose", "defeat"], ["lost", "defeat"], ["failure", "defeat"], ["fail", "defeat"], ["paused", "paused"], ["pause", "paused"]]);
/** 将路径归一化为合同身份；非法路径保留原值，交给执行校验报告安全错误。 */
function normalizePathForDefinition(value) { if (typeof value !== "string") return value; const raw = value.trim().replaceAll("\\", "/"); if (raw.startsWith("/") || raw.startsWith("//") || /^[a-z]:\//i.test(raw)) return raw.toLowerCase(); const parts = []; for (const part of raw.split("/")) { if (!part || part === ".") continue; if (part === "..") { if (parts.length === 0) return raw.toLowerCase(); parts.pop(); } else parts.push(part); } return parts.length ? parts.join("/").toLowerCase() : raw.toLowerCase(); }
/** 统一状态别名，保证 stateAnalysis 与 state_analysis 计算同一份合同身份。 */
function canonicalStateForDefinition(value) { if (typeof value !== "string") return value; const normalized = value.trim().toLowerCase().replaceAll("_", "-"); return STATE_ALIASES.get(normalized) ?? normalized; }
function firstDefined(value, aliases, fallback = null) { if (!isObject(value)) return fallback; for (const alias of aliases) if (Object.hasOwn(value, alias)) return value[alias]; return fallback; }
function normalizeStateAnalysisDefinition(value) { if (!isObject(value)) return value ?? null; const states = Array.isArray(value.states) ? value.states.map((state) => ({ state_id: canonicalStateForDefinition(firstDefined(state, ["state_id", "stateId"], "")), requirement: firstDefined(state, ["requirement", "applicability"], ""), reason: firstDefined(state, ["reason", "rationale"], "") })).sort((left, right) => String(left.state_id).localeCompare(String(right.state_id))) : []; return { status: firstDefined(value, ["status", "analysis_status"], ""), phase: firstDefined(value, ["phase", "analysis_phase"], ""), evidence: firstDefined(value, ["evidence", "analysis_evidence"], ""), evidence_sha256: firstDefined(value, ["evidence_sha256", "evidenceSha256"], ""), reference_target_sha256: firstDefined(value, ["reference_target_sha256", "referenceTargetSha256"], ""), analysis_id: firstDefined(value, ["analysis_id", "analysisId"], ""), completed_at: firstDefined(value, ["completed_at", "completedAt"], ""), states }; }
function normalizeComponentInventoryDefinition(value) { if (!isObject(value)) return value ?? null; const components = Array.isArray(value.components) ? value.components.map((component) => ({ component_id: firstDefined(component, ["component_id", "componentId"], ""), atomic_visual_key: firstDefined(component, ["atomic_visual_key", "atomicVisualKey"], ""), role: firstDefined(component, ["role", "component_role"], ""), reusable: component?.reusable, state_coverage: (Array.isArray(component?.state_coverage) ? component.state_coverage : (Array.isArray(component?.stateCoverage) ? component.stateCoverage : [])).map((state) => ({ state_id: canonicalStateForDefinition(firstDefined(state, ["state_id", "stateId"], "")), requirement: firstDefined(state, ["requirement", "applicability"], ""), reason: firstDefined(state, ["reason", "rationale"], "") })).sort((left, right) => String(left.state_id).localeCompare(String(right.state_id))), placements: (Array.isArray(component?.placements) ? component.placements : []).map((placement) => ({ placement_id: firstDefined(placement, ["placement_id", "placementId"], ""), interaction_required: firstDefined(placement, ["interaction_required", "interactionRequired"]), bounds: isObject(placement?.bounds) ? { x: placement.bounds.x, y: placement.bounds.y, width: placement.bounds.width, height: placement.bounds.height } : null })).sort((left, right) => String(left.placement_id).localeCompare(String(right.placement_id))) })).sort((left, right) => String(left.component_id).localeCompare(String(right.component_id))) : []; return { granularity: firstDefined(value, ["granularity", "asset_granularity"], ""), component_count: firstDefined(value, ["component_count", "componentCount"]), visible_instance_count: firstDefined(value, ["visible_instance_count", "visibleInstanceCount"]), delivery_mode: firstDefined(value, ["delivery_mode", "deliveryMode", "asset_delivery_mode"], ""), atlas_allowed: firstDefined(value, ["atlas_allowed", "atlasAllowed"]), created_at: firstDefined(value, ["created_at", "createdAt"], ""), components }; }
function normalizeAtlasSliceDefinition(value) { if (!isObject(value)) return value ?? null; const rect = isObject(value.rect) ? value.rect : value; const size = isObject(value.atlas_size ?? value.atlasSize) ? (value.atlas_size ?? value.atlasSize) : {}; return { atlas_asset_id: firstDefined(value, ["atlas_asset_id", "atlasAssetId"], ""), slice_id: firstDefined(value, ["slice_id", "sliceId"], ""), atlas_size: { width: size.width, height: size.height }, rect: { x: rect.x, y: rect.y, width: rect.width, height: rect.height } }; }
function normalizeExpectedAssetDefinition(value) { if (typeof value === "string") return { asset_id: value }; if (!isObject(value)) return { asset_id: "" }; return { asset_id: firstDefined(value, ["asset_id", "id", "name", "file", "path"], ""), component_id: firstDefined(value, ["component_id", "componentId"], ""), state_id: canonicalStateForDefinition(firstDefined(value, ["state_id", "stateId"], "")), asset_kind: firstDefined(value, ["asset_kind", "assetKind", "kind"], "visual"), asset_scope: firstDefined(value, ["asset_scope", "assetScope"], ""), atomic_visual_key: firstDefined(value, ["atomic_visual_key", "atomicVisualKey"], ""), source_file: normalizePathForDefinition(firstDefined(value, ["source_file", "sourceFile", "file"], "")), runtime_file: normalizePathForDefinition(firstDefined(value, ["runtime_file", "runtimeFile", "runtime_output_file", "runtimeOutputFile"], "")), mime_type: firstDefined(value, ["mime_type", "mimeType"]), width: value.width, height: value.height, alpha: value.alpha, sha256: firstDefined(value, ["sha256", "file_sha256"]), share_id: firstDefined(value, ["share_id", "shareId"]), atlas_slice: normalizeAtlasSliceDefinition(value.atlas_slice ?? value.atlasSlice) }; }
function normalizeHotspotDefinition(value) { if (!isObject(value)) return { hotspot_id: "", component_id: "", bounds: null }; const bounds = isObject(value.bounds) ? value.bounds : {}; return { hotspot_id: firstDefined(value, ["hotspot_id", "hotspotId"], ""), component_id: firstDefined(value, ["component_id", "componentId"], ""), placement_id: firstDefined(value, ["placement_id", "placementId"], ""), bounds: { x: bounds.x, y: bounds.y, width: bounds.width, height: bounds.height } }; }
function normalizeAtomicRequirementDefinition(value) { if (!isObject(value)) return { requirement_id: "" }; const placementIds = Array.isArray(value.placement_ids) ? value.placement_ids : (Array.isArray(value.placementIds) ? value.placementIds : []); return { requirement_id: firstDefined(value, ["requirement_id", "requirementId"], ""), annotation_number: firstDefined(value, ["annotation_number", "annotationNumber"], ""), region_id: firstDefined(value, ["region_id", "regionId"], ""), atomic_visual_key: firstDefined(value, ["atomic_visual_key", "atomicVisualKey"], ""), component_id: firstDefined(value, ["component_id", "componentId"], ""), state_id: canonicalStateForDefinition(firstDefined(value, ["state_id", "stateId"], "")), production_method: firstDefined(value, ["production_method", "productionMethod"], ""), delivery_kind: firstDefined(value, ["delivery_kind", "deliveryKind"], ""), asset_id: firstDefined(value, ["asset_id", "assetId"], ""), source_file: normalizePathForDefinition(firstDefined(value, ["source_file", "sourceFile"], "")), runtime_file: normalizePathForDefinition(firstDefined(value, ["runtime_file", "runtimeFile"], "")), placement_ids: placementIds.slice().sort() }; }
function normalizeRuntimeImplementationDefinition(value) { if (!isObject(value)) return value ?? null; const integrationFiles = Array.isArray(value.integration_files) ? value.integration_files : (Array.isArray(value.integrationFiles) ? value.integrationFiles : []); return { kind: value.kind ?? "", integration_files: integrationFiles.map(normalizePathForDefinition).sort(), description: value.description ?? "" }; }
function semanticDefinitionValue(field, value) { if (field === "state_analysis") return normalizeStateAnalysisDefinition(value); if (field === "component_inventory") return normalizeComponentInventoryDefinition(value); if (field === "asset_ids") return Array.isArray(value) ? value.slice().sort() : value; if (field === "expected_assets") return (Array.isArray(value) ? value.map(normalizeExpectedAssetDefinition) : []).sort((left, right) => `${left.component_id}\0${left.state_id}\0${left.asset_id}`.localeCompare(`${right.component_id}\0${right.state_id}\0${right.asset_id}`)); if (field === "interaction_hotspots") return (Array.isArray(value) ? value.map(normalizeHotspotDefinition) : []).sort((left, right) => `${left.component_id}\0${left.placement_id}\0${left.hotspot_id}`.localeCompare(`${right.component_id}\0${right.placement_id}\0${right.hotspot_id}`)); if (field === "atomic_image_requirements") return (Array.isArray(value) ? value.map(normalizeAtomicRequirementDefinition) : []).sort((left, right) => `${left.requirement_id}\0${left.component_id}\0${left.state_id}`.localeCompare(`${right.requirement_id}\0${right.component_id}\0${right.state_id}`)); if (field === "runtime_implementation") return normalizeRuntimeImplementationDefinition(value); return value; }
function regionFieldSources(region, field) { const sources = []; const aliases = REGION_FIELD_ALIASES[field] ?? [field]; for (const alias of aliases) if (isObject(region) && Object.hasOwn(region, alias)) sources.push({ source: alias, value: region[alias] }); if (NESTED_CONTRACT_FIELDS.has(field)) for (const nestedName of ["production_contract", "productionContract"]) { const nested = isObject(region?.[nestedName]) ? region[nestedName] : null; for (const alias of aliases) if (nested && Object.hasOwn(nested, alias)) sources.push({ source: `${nestedName}.${alias}`, value: nested[alias] }); } return sources; }
/** 返回验证器实际使用的规范化区域合同，哈希和执行门共用此语义。 */
export function normalizeVisualRegionDefinition(region = {}) { return Object.fromEntries(REGION_DEFINITION_FIELDS.map((field) => { const source = regionFieldSources(region, field)[0]; return [field, semanticDefinitionValue(field, source?.value ?? null)]; })); }
/** 检测 snake/camel/nested 三种写法是否同时出现且取值冲突。 */
export function getVisualRegionDefinitionAliasConflicts(region = {}) { const conflicts = []; for (const field of REGION_DEFINITION_FIELDS) { const sources = regionFieldSources(region, field); if (sources.length < 2) continue; const first = canonicalize(semanticDefinitionValue(field, sources[0].value)); if (sources.slice(1).some((entry) => canonicalize(semanticDefinitionValue(field, entry.value)) !== first)) conflicts.push({ field, sources: sources.map((entry) => entry.source) }); } return conflicts; }
/** 计算覆盖区域的稳定身份哈希；确认不参与哈希，避免确认内容自引用。 */
export function computeRegionDefinitionSha256(region) { return `sha256:${createHash("sha256").update(canonicalize(normalizeVisualRegionDefinition(region))).digest("hex")}`; }
/** 生成“左原图+右说明栏”的确定性 PNG；左侧只有框、编号和原子 placement 标记。 */
export function renderEffectImageAnnotation(originalBytes, originalPath, canvas, regions) { const sortedRegions = regions.slice().sort((left, right) => left.annotation_number - right.annotation_number); const metadata = { regions: sortedRegions.map((region) => { const production = annotationProductionContract(region); return { region_id: region.id, annotation_number: region.annotation_number, scene_id: region.scene_id, state_id: region.state_id, plan_mode: region.implementation_plan?.mode ?? "", summary: region.implementation_plan?.summary ?? "", production_method: production.production_method, production_origin: production.production_origin, delivery_kind: production.delivery_kind, production_label: production.label, region_definition_sha256: computeRegionDefinitionSha256(region), atomic_requirements_sha256: `sha256:${createHash("sha256").update(canonicalize(deriveAtomicImageRequirements(region))).digest("hex")}`, placement_ids: normalizeAtomicComponents(region).flatMap((component) => component.placements.map((placement) => placement.placement_id)).sort(), atomic_image_requirements: deriveAtomicImageRequirements(region) }; }) }; return renderRasterAnnotation(originalBytes, canvas, sortedRegions, metadata, PLAN_COLORS, PLAN_LABELS); }
