import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdir, mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import test from "node:test";
import { computeRegionDefinitionSha256 } from "./effect_image_annotation_core.mjs";
import { decodePngRgba, encodePngRgba } from "./effect_image_raster.mjs";
import { computeVisualAnnotationIdentitySha256, computeVisualAnnotationMetadataSha256, computeVisualConfirmationSha256, computeVisualUserMessageSha256 } from "../../phaser4-game-workflow-control/scripts/visual-decomposition-confirmation.mjs";
import { AUTOMATIC_LAYOUT_DECISION_METHOD, AUTOMATIC_LAYOUT_DECISION_SCHEMA } from "./automatic-layout-decision.mjs";
import { main } from "./generate_layout_annotation.mjs";

/** 计算测试文件的标准 SHA。 */
function sha256(bytes) { return `sha256:${createHash("sha256").update(bytes).digest("hex")}`; }
/** 构造最小但完整的 Stage A 确认文件链，布局生成器必须逐文件复算它。 */
async function fixture() {
  // 生成器会为根视口和每个确认元素绘制短编号；fixture 画布留出真实标签的避让空间。
  const root = await mkdtemp(join(tmpdir(), "layout-generator-")); const original = encodePngRgba(180, 100, Buffer.alloc(180 * 100 * 4, 220)); const targetSha = sha256(original); await writeFile(join(root, "reference.png"), original);
  const region = { id: "panel-region", annotation_number: 1, scene_id: "main", state_id: "default", bounds: { x: 2, y: 2, width: 30, height: 24 }, owner_type: "runtime-rendered", implementation_plan: { mode: "runtime-program", summary: "程序布局" } };
  const elements = [{ element_id: "panel-element", element_type: "container", role: "container", bounds: { x: 2, y: 2, width: 30, height: 24 }, scene_id: region.scene_id, state_id: region.state_id, region_id: region.id, component_id: "panel", placement_id: "panel-placement", empty_container: false }, { element_id: "button-element", element_type: "component", role: "component", bounds: { x: 6, y: 6, width: 10, height: 8 }, scene_id: region.scene_id, state_id: region.state_id, region_id: region.id, component_id: "button", placement_id: "button-placement", parent_element_id: "panel-element" }];
  // 该节点故意与 proposal 元素不同，用来证明布局入口不会读取预存 layout_nodes。
  const nodes = [{ layout_node_id: "ignored-manifest-node", region_id: region.id, parent_layout_node_id: "viewport", target_bounds: { x: 1, y: 1, width: 2, height: 2 }, layout_role: "container" }];
  const regionSnapshot = { annotation_number: region.annotation_number, region_id: region.id, scene_id: region.scene_id, state_id: region.state_id, region_definition_sha256: computeRegionDefinitionSha256(region) };
  const annotationMetadata = { schema: "effect-image-annotation/png/1", layout: "image-plus-right-panel", width: 50, height: 30, panel_content_complete: true, original_sha256: targetSha, regions: [regionSnapshot] }; const annotationBytes = encodePngRgba(50, 30, Buffer.alloc(50 * 30 * 4, 240), annotationMetadata); const annotationSha = sha256(annotationBytes); const annotationMetadataSha = computeVisualAnnotationMetadataSha256(annotationMetadata); const annotationIdentitySha = computeVisualAnnotationIdentitySha256(annotationSha, 50, 30, annotationMetadataSha, annotationMetadata.schema, annotationMetadata.layout); const annotationFile = "evidence/v2/decomposition.png"; await mkdir(join(root, "evidence/v2"), { recursive: true }); await writeFile(join(root, annotationFile), annotationBytes);
  const proposalFile = "evidence/v2/proposal.json"; const proposal = { proposal_id: "proposal-1", target_sha256: targetSha, scene_id: region.scene_id, state_id: region.state_id, annotation_file: annotationFile, annotation_sha256: annotationSha, decomposition_elements: elements, regions: [regionSnapshot], technical_analysis: { schema_version: "1", decomposition_elements: elements, regions: [{ annotation_number: region.annotation_number, region_id: region.id, scene_id: region.scene_id, state_id: region.state_id, region_definition_sha256: regionSnapshot.region_definition_sha256, decomposition_elements: elements }] } }; const proposalBytes = Buffer.from(JSON.stringify(proposal)); await writeFile(join(root, proposalFile), proposalBytes); const proposalSha = sha256(proposalBytes);
  const userText = "确认拆解后进入布局"; const acceptedAt = "2026-08-15T00:20:00Z"; const decisionFile = "evidence/v2/decision.json"; const decision = { author_role: "user", resolution_status: "resolved", resolved_from: "USER_INPUT_REQUIRED", status: "accepted", confirmation_mode: "manual", confirmation_id: "decomp-1", proposal_id: proposal.proposal_id, proposal_sha256: proposalSha, user_statement: userText, user_message_sha256: computeVisualUserMessageSha256(userText), accepted_at: acceptedAt, target_sha256: targetSha, scene_id: region.scene_id, state_id: region.state_id, regions: [regionSnapshot] }; const decisionBytes = Buffer.from(JSON.stringify(decision)); await writeFile(join(root, decisionFile), decisionBytes); const decisionSha = sha256(decisionBytes);
  const receiptFile = ".phaser-workflow/user-resolutions/decomp-receipt.json"; const receipt = { message_id: "message-1", thread_id: "thread-1", author_role: "user", resolution_status: "resolved", resolved_from: "USER_INPUT_REQUIRED", resolution_id: "resolution-1", user_statement: userText, user_message_sha256: computeVisualUserMessageSha256(userText), decision_record_sha256: decisionSha, accepted_at: acceptedAt, target_sha256: targetSha, scene_id: region.scene_id, state_id: region.state_id }; const receiptBytes = Buffer.from(JSON.stringify(receipt)); await mkdir(dirname(join(root, receiptFile)), { recursive: true }); await writeFile(join(root, receiptFile), receiptBytes); const receiptSha = sha256(receiptBytes);
  const record = { confirmation_schema: "visual-decomposition-confirmation/1.0", confirmation_id: "decomp-1", status: "accepted", confirmation_mode: "manual", proposal_id: proposal.proposal_id, proposal_sha256: proposalSha, proposal_file: proposalFile, annotation_file: annotationFile, annotation_sha256: annotationSha, annotation_mime: "image/png", annotation_width: 50, annotation_height: 30, annotation_schema: annotationMetadata.schema, annotation_layout: annotationMetadata.layout, annotation_metadata_sha256: annotationMetadataSha, annotation_identity_sha256: annotationIdentitySha, decision_record_file: decisionFile, decision_record_sha256: decisionSha, user_decision_receipt_file: receiptFile, user_decision_receipt_sha256: receiptSha, target_sha256: targetSha, scene_id: region.scene_id, state_id: region.state_id, user_original_text: userText, user_message_sha256: computeVisualUserMessageSha256(userText), accepted_at: acceptedAt };
  record.confirmation_sha256 = computeVisualConfirmationSha256(record);
  const layoutDecisionFile = "evidence/v2/automatic-layout-decision.json"; const layoutDecision = { decision_schema: AUTOMATIC_LAYOUT_DECISION_SCHEMA, decision_id: "layout-decision-1", decision_method: AUTOMATIC_LAYOUT_DECISION_METHOD, target_sha256: targetSha, scene_id: region.scene_id, state_id: region.state_id, decomposition_confirmation_id: record.confirmation_id, decomposition_confirmation_sha256: record.confirmation_sha256, proposal_sha256: proposalSha, elements: [{ element_id: "panel-element", horizontal_alignment: "left", vertical_alignment: "top" }, { element_id: "button-element", horizontal_alignment: "center", vertical_alignment: "center" }] }; const layoutDecisionBytes = Buffer.from(JSON.stringify(layoutDecision)); await writeFile(join(root, layoutDecisionFile), layoutDecisionBytes); const layoutDecisionSha = sha256(layoutDecisionBytes);
  const manifest = { reference_target: { original_file: "reference.png", target_sha256: targetSha }, coverage_audit: { regions: [{ ...region, confirmation: record }] }, scene_reconstruction_contract: { target_conditions: { scene_id: "main", state_id: "default", target_sha256: targetSha, viewport: { width: 180, height: 100 } }, visual_decomposition_confirmation: record, layout_decomposition: { layout_nodes: nodes } } }; const manifestFile = "manifest.json"; await writeFile(join(root, manifestFile), JSON.stringify(manifest));
  return { root, manifest, manifestFile, record, proposal, proposalFile, decision, decisionFile, receipt, receiptFile, layoutDecision, layoutDecisionFile, layoutDecisionSha, targetSha, nodes, elements, args() { return [manifestFile, "--project-root", root, "--scene-id", "main", "--state-id", "default", "--output", "evidence/v2/layout.png", "--decomposition-confirmation-id", record.confirmation_id, "--decomposition-confirmation-sha256", record.confirmation_sha256, "--proposal-sha256", record.proposal_sha256, "--layout-decision-file", layoutDecisionFile, "--layout-decision-sha256", this.layoutDecisionSha]; } };
}

/** 重写已确认 proposal 及其后续决定身份，测试遗漏/新增节点会被元素集合门拒绝。 */
async function rewriteProposal(value, elements, rebind = true) { value.proposal.decomposition_elements = elements; value.proposal.technical_analysis.decomposition_elements = elements; value.proposal.technical_analysis.regions[0].decomposition_elements = elements; const proposalBytes = Buffer.from(JSON.stringify(value.proposal)); await writeFile(join(value.root, value.proposalFile), proposalBytes); if (!rebind) return; value.record.proposal_sha256 = sha256(proposalBytes); value.decision.proposal_sha256 = value.record.proposal_sha256; const decisionBytes = Buffer.from(JSON.stringify(value.decision)); await writeFile(join(value.root, value.decisionFile), decisionBytes); value.record.decision_record_sha256 = sha256(decisionBytes); value.receipt.decision_record_sha256 = value.record.decision_record_sha256; const receiptBytes = Buffer.from(JSON.stringify(value.receipt)); await writeFile(join(value.root, value.receiptFile), receiptBytes); value.record.user_decision_receipt_sha256 = sha256(receiptBytes); value.record.confirmation_sha256 = computeVisualConfirmationSha256(value.record); value.layoutDecision.proposal_sha256 = value.record.proposal_sha256; value.layoutDecision.decomposition_confirmation_sha256 = value.record.confirmation_sha256; const layoutDecisionBytes = Buffer.from(JSON.stringify(value.layoutDecision)); await writeFile(join(value.root, value.layoutDecisionFile), layoutDecisionBytes); value.layoutDecisionSha = sha256(layoutDecisionBytes); value.manifest.scene_reconstruction_contract.visual_decomposition_confirmation = value.record; value.manifest.coverage_audit.regions[0].confirmation = value.record; await writeFile(join(value.root, value.manifestFile), JSON.stringify(value.manifest)); }

test("未确认、pending 或伪造的拆解确认不能启动布局生成", async () => { for (const mutate of [value => { value.record.status = "pending"; }, value => { value.record.confirmation_sha256 = `sha256:${"f".repeat(64)}`; }]) { const value = await fixture(); mutate(value); await writeFile(join(value.root, value.manifestFile), JSON.stringify(value.manifest)); assert.equal(await main(value.args()), 1); } });
test("完整 Stage A 文件链通过后才生成布局 PNG，且忽略预存 layout_nodes", async () => { const value = await fixture(); assert.equal(await main(value.args()), 0); const bytes = await readFile(join(value.root, "evidence/v2/layout.png")); const decoded = decodePngRgba(bytes); assert.equal(decoded.metadata.decomposition_confirmation_id, value.record.confirmation_id); assert.equal(decoded.metadata.target_sha256, value.targetSha); assert.deepEqual(decoded.metadata.nodes.filter((node) => !node.is_root_container).map((node) => node.element_id), value.elements.map((element) => element.element_id)); assert.deepEqual(decoded.metadata.nodes.find((node) => node.element_id === "button-element").axis_alignment, { horizontal: "center", vertical: "center" }); assert.deepEqual(decoded.metadata.nodes.map((node) => ({ marker_id: node.marker_id, parent_marker_id: node.parent_marker_id, is_root_container: node.is_root_container })), [{ marker_id: "L01", parent_marker_id: "R01", is_root_container: false }, { marker_id: "L02", parent_marker_id: "L01", is_root_container: false }, { marker_id: "R01", parent_marker_id: null, is_root_container: true }]); assert(decoded.metadata.visible_rows.some((row) => row.marker_id === "L01" && row.text.includes("停靠="))); assert(decoded.metadata.visible_rows.some((row) => row.marker_id === "L02" && row.text.includes("停靠="))); assert(decoded.metadata.visible_rows.some((row) => row.marker_id === "R01" && row.text.includes("无上级"))); assert(!decoded.metadata.nodes.some((node) => node.layout_node_id === "ignored-manifest-node")); assert.equal(sha256(await readFile(join(value.root, "reference.png"))), value.targetSha, "布局阶段不得改写视觉参考图"); });
test("已确认 proposal 遗漏或新增元素时未重新确认则拒绝生成", async () => { for (const omit of [true, false]) { const value = await fixture(); const elements = omit ? [value.elements[0]] : [...value.elements, { ...value.elements[1], element_id: "extra-element" }]; await rewriteProposal(value, elements, false); assert.equal(await main(value.args()), 1); } });
test("重新确认后的元素 bounds 变化会生成不同布局结果", async () => { const value = await fixture(); assert.equal(await main(value.args()), 0); const original = await readFile(join(value.root, "evidence/v2/layout.png")); const changed = value.elements.map((element) => element.element_id === "button-element" ? { ...element, bounds: { ...element.bounds, x: element.bounds.x + 3 } } : element); await rewriteProposal(value, changed, true); assert.equal(await main(value.args()), 0); const updated = await readFile(join(value.root, "evidence/v2/layout.png")); assert.notDeepEqual(updated, original); });
test("缺失或非法显式智能布局决策时必须关闭生成", async () => { const missing = await fixture(); assert.equal(await main(missing.args().slice(0, -4)), 1); const invalid = await fixture(); invalid.layoutDecision.elements[0].horizontal_alignment = "diagonal"; const bytes = Buffer.from(JSON.stringify(invalid.layoutDecision)); await writeFile(join(invalid.root, invalid.layoutDecisionFile), bytes); invalid.layoutDecisionSha = sha256(bytes); assert.equal(await main(invalid.args()), 1); });
test("智能布局决策遗漏、新增或调序元素时必须关闭生成", async () => { for (const mutate of [items => items.slice(1), items => [...items, { element_id: "fake-element", horizontal_alignment: "left", vertical_alignment: "top" }], items => [items[1], items[0]]]) { const value = await fixture(); value.layoutDecision.elements = mutate(value.layoutDecision.elements); const bytes = Buffer.from(JSON.stringify(value.layoutDecision)); await writeFile(join(value.root, value.layoutDecisionFile), bytes); value.layoutDecisionSha = sha256(bytes); assert.equal(await main(value.args()), 1); } });
