import assert from "node:assert/strict";
import { mkdir, mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import test from "node:test";
import { checkManifestFiles, main, validateManifest } from "./validate_visual_manifest.mjs";
import { CORE_TEMPLATES, OPTIONAL_TEMPLATES } from "../../phaser4-game-orchestrator/scripts/project_doc_templates.mjs";

const EMPTY_DOCUMENT_FINGERPRINT = "sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855";

/** 构造包含一个已验收资源的有效清单。 */
function validManifest() {
  const targetSha = EMPTY_DOCUMENT_FINGERPRINT;
  const candidateSha = "sha256:2222222222222222222222222222222222222222222222222222222222222222";
  return {
    schema_version: "1.3",
    effect_image_reconstruction: { applicability: "effect-image", lifecycle: "v5-complete" },
    visual_baseline: { id: "fox-world", version: "1.0.0", style_fingerprint: EMPTY_DOCUMENT_FINGERPRINT, document: "docs/visual-baseline.md", status: "frozen", anchor_evidence: ["evidence/visual/main-anchor.png"] },
    reference_target: { candidate_id: "mockup-a", original_file: "evidence/visual/mockup.png", target_sha256: targetSha, frozen_at: "2026-08-15T00:00:00Z", status: "frozen", scene_ids: ["main-gameplay"], state_ids: ["default"] },
    candidate_identity: { kind: "git", sha256: candidateSha },
    contract_reconciliation: {
      decision_id: "reconcile-1", reviewed_at: "2026-08-15T00:10:00Z", target_sha256: targetSha, candidate_sha256: candidateSha, status: "passed", rollback: "V1/module-audit",
      bindings: { gdd: "docs/GDD.md#v1", tdd: "docs/TDD.md#v1", gameplay_visual_contract: "visual-contract:v1", gameplay_function_contract: "function-contract:v1", layout_contract: "layout:v1", module_scene_ownership: "ownership:v1", budget_baseline: "budget:v1" },
      checks: ["scope", "state-machine", "input", "collision", "module-scene-ownership", "coordinate-space", "layout", "budget"].map((domain) => ({ domain, status: "passed", evidence: `evidence/reconcile/${domain}.md` })),
    },
    coverage_audit: { version: "1", reference_target_sha256: targetSha, canvases: [{ scene_id: "main-gameplay", state_id: "default", width: 390, height: 844 }], summaries: [{ scene_id: "main-gameplay", state_id: "default", coverage_ratio: 1, uncovered: [], status: "passed", evidence: "evidence/coverage/summary.md" }], regions: [{ id: "region-background", scene_id: "main-gameplay", state_id: "default", layer: "background", bounds: { x: 0, y: 0, width: 390, height: 844 }, owner_type: "runtime-rendered", owner_id: "scene-background", confirmation: { mode: "AUTO", reasons: [], evidence: "evidence/coverage/region-background.md" } }, { id: "region-hero", scene_id: "main-gameplay", state_id: "default", layer: "actors", bounds: { x: 10, y: 20, width: 64, height: 96 }, owner_type: "fixed-production-visual", owner_id: "asset-pipeline", asset_id: "hero-idle", confirmation: { mode: "AUTO", reasons: [], evidence: "evidence/coverage/region-hero.md" } }, { id: "region-score", scene_id: "main-gameplay", state_id: "default", layer: "hud", bounds: { x: 300, y: 10, width: 70, height: 30 }, owner_type: "runtime-data", owner_id: "score-state", confirmation: { mode: "AUTO", reasons: [], evidence: "evidence/coverage/region-score.md" } }] },
    fidelity_cases: [{ id: "main-default", target_sha256: targetSha, candidate_sha256: candidateSha, scene_id: "main-gameplay", state_id: "default", viewport: { width: 390, height: 844 }, dpr: 2, language: "zh-CN", random_seed: 42, input_trace: "traces/main-default.json", animation_sample: "stable-frame:120", layout_contract_version: "1.1.0", visual_baseline_version: "1.0.0", reference_evidence: ["evidence/visual/reference.png"], candidate_evidence: ["evidence/visual/candidate.png"], tolerance: { unit: "logical-px", value: 2 }, exception_ids: [], conclusion: "passed" }],
    budgets: { max_texture_size: 4096, texture_memory_mb: 64, package_size_mb: 50, max_atlases: 8, max_frames: 512, animation_sample_fps: 24, max_overdraw: 3, max_draw_calls: 100 },
    assets: [{ id: "hero-idle", texture_key: "hero-idle", ownership_type: "fixed-production-visual", coverage_region_ids: ["region-hero"], scene_id: "main-gameplay", route: "frame-animation", status: "accepted", visual_baseline_id: "fox-world", visual_baseline_version: "1.0.0", style_fingerprint: EMPTY_DOCUMENT_FINGERPRINT, source_file: "art/hero.aseprite", license_record: "docs/license.md", runtime_outputs: ["public/assets/hero.png"], phaser_evidence: "evidence/phaser.png", gameplay_visual_evidence: "evidence/gameplay.mp4", consistency_evidence: ["evidence/visual/hero-consistency.png"] }],
  };
}

/** 构造不启用效果图还原的普通资源清单。 */
function validOrdinaryManifest() {
  const manifest = validManifest(); manifest.effect_image_reconstruction = { applicability: "not-applicable", lifecycle: "not-applicable" };
  for (const field of ["reference_target", "candidate_identity", "contract_reconciliation", "coverage_audit", "fidelity_cases"]) delete manifest[field];
  delete manifest.assets[0].ownership_type; delete manifest.assets[0].coverage_region_ids;
  return manifest;
}

/** 构造包含完整生成包的 AI 合成栅格清单。 */
function validAiManifest() {
  const manifest = validManifest(); const asset = manifest.assets[0]; asset.route = "ai-composite-raster";
  asset.generation_record = { record_id: "gen-hero-1", generator: "image-pipeline", generator_version: "1", created_at: "2026-08-15T00:00:00Z", command_or_recipe: "render hero-idle", input_sources: ["prompt:hero-idle"], parameters: { size: "64x96" }, global_prompt_prefix: "冻结前缀", asset_prompt: "主角", state_prompt: "待机", negative_prompt: "禁止写实", model: "image-model", model_version: "1", seed: 42, reference_inputs: ["evidence/visual/ai-reference.png"], postprocess: ["清理边缘"] };
  return manifest;
}

/** 创建文件检查所需的空夹具。 */
async function createFixtureFiles(root, includeAi = false) {
  const paths = ["docs/visual-baseline.md", "evidence/visual/main-anchor.png", "evidence/visual/mockup.png", "evidence/visual/reference.png", "evidence/visual/candidate.png", "evidence/coverage/summary.md", "evidence/coverage/region-background.md", "evidence/coverage/region-hero.md", "evidence/coverage/region-score.md", "art/hero.aseprite", "docs/license.md", "public/assets/hero.png", "evidence/phaser.png", "evidence/gameplay.mp4", "evidence/visual/hero-consistency.png", ...["scope", "state-machine", "input", "collision", "module-scene-ownership", "coordinate-space", "layout", "budget"].map((domain) => `evidence/reconcile/${domain}.md`)];
  if (includeAi) paths.push("evidence/visual/ai-reference.png");
  for (const path of paths) { const target = join(root, path); await mkdir(dirname(target), { recursive: true }); await writeFile(target, ""); }
}

test("有效清单通过", () => assert.deepEqual(validateManifest(validManifest()), []));
test("非效果图 1.3 清单通过", () => assert.deepEqual(validateManifest(validOrdinaryManifest()), []));
test("effect-image V3-ready 允许 fidelity case 尚未产生", () => { const manifest = validManifest(); manifest.effect_image_reconstruction.lifecycle = "v3-ready"; manifest.fidelity_cases = []; assert.deepEqual(validateManifest(manifest), []); });
test("V5 complete 必须有全部通过的 fidelity case", () => { const missing = validManifest(); missing.fidelity_cases = []; assert(validateManifest(missing).some((item) => item.includes("fidelity_cases 必须是非空数组"))); const failed = validManifest(); failed.fidelity_cases[0].conclusion = "failed"; assert(validateManifest(failed).some((item) => item.includes("必须全部 passed"))); });
test("V5 fidelity 必须逐冻结 scene/state 组合覆盖", () => { const manifest = validManifest(); manifest.reference_target.state_ids.push("paused"); manifest.coverage_audit.canvases.push({ scene_id: "main-gameplay", state_id: "paused", width: 390, height: 844 }); manifest.coverage_audit.summaries.push({ scene_id: "main-gameplay", state_id: "paused", coverage_ratio: 1, uncovered: [], status: "passed", evidence: "evidence/coverage/paused-summary.md" }); manifest.coverage_audit.regions.push({ ...structuredClone(manifest.coverage_audit.regions[0]), id: "region-paused", state_id: "paused" }); assert(validateManifest(manifest).some((item) => item.includes("main-gameplay/paused"))); });
test("项目模板默认生成非效果图 1.3 资源清单", () => { assert(CORE_TEMPLATES["GDD.md"].includes("完整场景与功能清单")); assert(CORE_TEMPLATES["TDD.md"].includes("functional_status")); assert(CORE_TEMPLATES["visual-baseline.md"].includes("不追加 V2b、V4、V5 证据")); assert(CORE_TEMPLATES["visual-design.md"].includes("可追加的视觉方向")); assert(!OPTIONAL_TEMPLATES.assets["asset-license-register.md"].includes("对 `docs/visual-design.md` 计算")); const template = JSON.parse(OPTIONAL_TEMPLATES.assets["visual-assets.json"]); assert.equal(template.schema_version, "1.3"); assert.equal(template.visual_baseline.document, "docs/visual-baseline.md"); assert.deepEqual(template.effect_image_reconstruction, { applicability: "not-applicable", lifecycle: "not-applicable" }); assert(!("reference_target" in template)); });
test("合同回对门缺项、未通过或身份漂移时失败", () => { const missing = validManifest(); missing.contract_reconciliation.checks.pop(); assert(validateManifest(missing).some((item) => item.includes("缺少已通过领域"))); const failed = validManifest(); failed.contract_reconciliation.status = "failed"; assert(validateManifest(failed).some((item) => item.includes("必须为 passed"))); const drifted = validManifest(); drifted.contract_reconciliation.candidate_sha256 = `sha256:${"9".repeat(64)}`; assert(validateManifest(drifted).some((item) => item.includes("当前候选 SHA 不一致"))); });
test("ownership 覆盖规则拒绝运行内容位图化", () => { const manifest = validManifest(); manifest.coverage_audit.regions[2].asset_id = "hero-idle"; assert(validateManifest(manifest).some((item) => item.includes("禁止映射生产位图"))); });
test("覆盖区域要求几何和 AUTO 判定证据", () => { const bounds = validManifest(); delete bounds.coverage_audit.regions[0].bounds; assert(validateManifest(bounds).some((item) => item.includes("bounds 必须"))); const evidence = validManifest(); delete evidence.coverage_audit.regions[0].confirmation.evidence; assert(validateManifest(evidence).some((item) => item.includes("AUTO 自动判定依据"))); });
test("coverage 与 fidelity 必须位于冻结目标范围", () => { const coverage = validManifest(); coverage.coverage_audit.regions[0].scene_id = "unknown-scene"; assert(validateManifest(coverage).some((item) => item.includes("scene_id 不在 reference_target"))); const fidelity = validManifest(); fidelity.fidelity_cases[0].state_id = "unknown-state"; assert(validateManifest(fidelity).some((item) => item.includes("state_id 不在 reference_target"))); });
test("coverage 完整性拒绝 1x1、缺目标状态和越界区域", () => { const tiny = validManifest(); tiny.coverage_audit.regions = [{ ...tiny.coverage_audit.regions[0], bounds: { x: 0, y: 0, width: 1, height: 1 } }]; assert(validateManifest(tiny).some((item) => item.includes("并集面积不足"))); const missing = validManifest(); missing.reference_target.state_ids.push("paused"); assert(validateManifest(missing).some((item) => item.includes("缺少目标组合"))); const overflow = validManifest(); overflow.coverage_audit.regions[1].bounds.x = 380; assert(validateManifest(overflow).some((item) => item.includes("bounds 超出目标画布"))); });
test("coverage 重叠矩形不得重复累计为完整画布", () => { const manifest = validManifest(); manifest.coverage_audit.regions = [structuredClone(manifest.coverage_audit.regions[0]), structuredClone(manifest.coverage_audit.regions[0])]; manifest.coverage_audit.regions[0].bounds = { x: 0, y: 0, width: 390, height: 422 }; manifest.coverage_audit.regions[1].id = "region-overlap"; manifest.coverage_audit.regions[1].bounds = { x: 0, y: 0, width: 390, height: 422 }; assert(validateManifest(manifest).some((item) => item.includes("矩形并集面积不足"))); });
test("固定视觉必须映射资源且资产必须反向绑定区域", () => { const missing = validManifest(); missing.coverage_audit.regions[1].asset_id = "unknown"; assert(validateManifest(missing).some((item) => item.includes("映射已声明正式资源"))); const stale = validManifest(); stale.assets[0].coverage_region_ids = ["region-score"]; assert(validateManifest(stale).some((item) => item.includes("未映射到该资源"))); });
test("固定视觉覆盖映射必须双向完全一致", () => { const manifest = validManifest(); manifest.coverage_audit.regions.push({ ...structuredClone(manifest.coverage_audit.regions[1]), id: "region-hero-shadow" }); assert(validateManifest(manifest).some((item) => item.includes("缺少映射到该资源"))); });
test("资产 coverage_region_ids 不得重复", () => { const manifest = validManifest(); manifest.assets[0].coverage_region_ids.push("region-hero"); assert(validateManifest(manifest).some((item) => item.includes("coverage_region_ids 不得重复"))); });
test("effect-image 清单允许同时包含未映射普通资产", () => { const manifest = validManifest(); const ordinary = { ...manifest.assets[0], id: "boot-logo", texture_key: "boot-logo", scene_id: "boot", runtime_outputs: ["public/assets/boot-logo.png"] }; delete ordinary.ownership_type; delete ordinary.coverage_region_ids; manifest.assets.push(ordinary); assert.deepEqual(validateManifest(manifest), []); });
test("孤立还原字段不得伪造映射", () => { const manifest = validManifest(); const isolated = { ...manifest.assets[0], id: "boot-logo", texture_key: "boot-logo", scene_id: "boot", runtime_outputs: ["public/assets/boot-logo.png"], coverage_region_ids: ["region-hero"] }; manifest.assets.push(isolated); assert(validateManifest(manifest).some((item) => item.includes("未被 fixed coverage 引用"))); });
test("条件编号确认必须绑定编号图文件、哈希与决定", () => { const manifest = validManifest(); manifest.coverage_audit.regions[0].confirmation = { mode: "USER_DECISION", reasons: ["ambiguous-boundary"] }; const errors = validateManifest(manifest); assert(errors.some((item) => item.includes("numbered_image_file"))); assert(errors.some((item) => item.includes("numbered_image_sha256"))); assert(errors.some((item) => item.includes("decision_id"))); });
test("重复合同领域、覆盖和 fidelity ID 失败", () => { const gate = validManifest(); gate.contract_reconciliation.checks.push(structuredClone(gate.contract_reconciliation.checks[0])); assert(validateManifest(gate).some((item) => item.includes("domain 重复"))); const coverage = validManifest(); coverage.coverage_audit.regions.push(structuredClone(coverage.coverage_audit.regions[0])); assert(validateManifest(coverage).some((item) => item.includes("id 重复"))); const fidelity = validManifest(); fidelity.fidelity_cases.push(structuredClone(fidelity.fidelity_cases[0])); assert(validateManifest(fidelity).some((item) => item.includes("id 重复"))); });
test("parity 身份变化使旧证据失效", () => { const target = validManifest(); target.fidelity_cases[0].target_sha256 = `sha256:${"3".repeat(64)}`; assert(validateManifest(target).some((item) => item.includes("冻结目标 SHA 不一致"))); const candidate = validManifest(); candidate.fidelity_cases[0].candidate_sha256 = `sha256:${"4".repeat(64)}`; assert(validateManifest(candidate).some((item) => item.includes("当前候选 SHA 不一致"))); });
test("fidelity 必须绑定根视觉基线版本", () => { const manifest = validManifest(); manifest.fidelity_cases[0].visual_baseline_version = "2.0.0"; assert(validateManifest(manifest).some((item) => item.includes("根 visual_baseline.version"))); });
test("所有资源状态都要求场景归属", () => { for (const status of ["planned", "producing", "review", "accepted", "rejected", "replaced"]) { const manifest = validManifest(); manifest.assets[0].status = status; delete manifest.assets[0].scene_id; assert(validateManifest(manifest).some((item) => item.includes("scene_id 或 shared")), status); } });
test("公共资源要求稳定复用或运行必需", () => { const valid = validManifest(); delete valid.assets[0].scene_id; valid.assets[0].shared = true; valid.assets[0].shared_scene_ids = ["main-gameplay", "result"]; assert.deepEqual(validateManifest(valid), []); const oneScene = validManifest(); delete oneScene.assets[0].scene_id; oneScene.assets[0].shared = true; oneScene.assets[0].shared_scene_ids = ["main-gameplay"]; assert(validateManifest(oneScene).some((item) => item.includes("至少两个"))); const runtime = validManifest(); delete runtime.assets[0].scene_id; runtime.assets[0].shared = true; runtime.assets[0].shared_reason = "runtime-required"; assert.deepEqual(validateManifest(runtime), []); });
test("场景归属与公共归属不得混用", () => { const manifest = validManifest(); manifest.assets[0].shared = true; manifest.assets[0].shared_scene_ids = ["main-gameplay", "result"]; assert(validateManifest(manifest).some((item) => item.includes("二选一"))); });
test("重复纹理键和输出路径同时报告", () => { const manifest = validManifest(); manifest.assets.push({ ...manifest.assets[0], id: "hero-run" }); const errors = validateManifest(manifest); assert(errors.some((item) => item.includes("texture_key 重复"))); assert(errors.some((item) => item.includes("路径重复"))); });
test("已验收资源要求证据", () => { const manifest = validManifest(); delete manifest.assets[0].phaser_evidence; assert(validateManifest(manifest).some((item) => item.includes("phaser_evidence"))); });
test("视觉基线必须存在且冻结", () => { const missing = validManifest(); delete missing.visual_baseline; assert(validateManifest(missing).includes("visual_baseline 必须是对象")); const draft = validManifest(); draft.visual_baseline.status = "draft"; assert(validateManifest(draft).some((item) => item.includes("status 必须为 frozen"))); });
test("风格指纹格式固定", () => { const manifest = validManifest(); manifest.visual_baseline.style_fingerprint = "sha256:ABC"; assert(validateManifest(manifest).some((item) => item.includes("64 位小写十六进制"))); });
test("阶段证据文档不得作为冻结基线哈希正文", () => { const manifest = validManifest(); manifest.visual_baseline.document = "docs/visual-design.md"; assert(validateManifest(manifest).some((item) => item.includes("不可变 docs/visual-baseline.md"))); });
test("资源基线绑定必须一致", () => { for (const [field, value] of [["visual_baseline_version", "2.0.0"], ["style_fingerprint", "sha256:drifted"]]) { const manifest = validManifest(); manifest.assets[0][field] = value; assert(validateManifest(manifest).some((item) => item.includes(`${field} 与`))); } });
test("AI 生成包字段完整", () => { assert.deepEqual(validateManifest(validAiManifest()), []); const manifest = validAiManifest(); delete manifest.assets[0].generation_record.global_prompt_prefix; assert(validateManifest(manifest).some((item) => item.includes("global_prompt_prefix"))); });
test("任意路线使用 generation_record 时必须提供完整公共生成身份", () => { const forged = validManifest(); delete forged.assets[0].source_file; forged.assets[0].generation_record = { x: 1 }; assert(validateManifest(forged).some((item) => item.includes("generation_record.record_id"))); const generated = validManifest(); delete generated.assets[0].source_file; generated.assets[0].generation_record = { record_id: "gen-1", generator: "aseprite-cli", generator_version: "1.3", created_at: "2026-08-15T00:00:00Z", command_or_recipe: "aseprite -b hero.aseprite --save-as hero.png", input_sources: ["spec:hero-idle"], parameters: { scale: 1 } }; assert.deepEqual(validateManifest(generated), []); });
test("预算必须是正数", () => { const manifest = validManifest(); manifest.budgets.max_texture_size = null; assert(validateManifest(manifest).some((item) => item.includes("max_texture_size 必须是正数"))); });
test("文件检查覆盖存在性、哈希与 AI 引用", async () => { const root = await mkdtemp(join(tmpdir(), "visual-manifest-")); const manifest = validAiManifest(); assert((await checkManifestFiles(manifest, root)).some((item) => item.includes("文件不存在"))); await createFixtureFiles(root, true); assert.deepEqual(await checkManifestFiles(manifest, root), []); await writeFile(join(root, "docs/visual-baseline.md"), "修改"); assert((await checkManifestFiles(manifest, root)).some((item) => item.includes("SHA-256 不一致"))); });
test("编号图文件缺失或哈希不匹配时文件检查失败", async () => { const root = await mkdtemp(join(tmpdir(), "visual-numbered-")); const manifest = validManifest(); manifest.coverage_audit.regions[0].confirmation = { mode: "USER_DECISION", reasons: ["ambiguous-boundary"], numbered_image_file: "evidence/coverage/numbered.png", numbered_image_version: "1", numbered_image_sha256: EMPTY_DOCUMENT_FINGERPRINT, decision_id: "decision-1" }; await createFixtureFiles(root); assert((await checkManifestFiles(manifest, root)).some((item) => item.includes("numbered_image_file 文件不存在"))); const path = join(root, "evidence/coverage/numbered.png"); await mkdir(dirname(path), { recursive: true }); await writeFile(path, "changed"); assert((await checkManifestFiles(manifest, root)).some((item) => item.includes("numbered_image_sha256 与文件"))); });
test("文件检查拒绝路径逃逸", async () => { const root = await mkdtemp(join(tmpdir(), "visual-manifest-")); const manifest = validManifest(); manifest.visual_baseline.document = "../outside.md"; assert((await checkManifestFiles(manifest, root)).some((item) => item.includes("路径逃逸"))); });
test("错误 assets 容器安全跳过文件检查", async () => { const root = await mkdtemp(join(tmpdir(), "visual-manifest-")); const manifest = validManifest(); manifest.assets = 42; await createFixtureFiles(root); assert(validateManifest(manifest).includes("assets 必须是数组")); assert.deepEqual(await checkManifestFiles(manifest, root), []); });
test("CLI 对结构错误返回非零", async () => { const root = await mkdtemp(join(tmpdir(), "visual-manifest-")); const path = join(root, "visual-assets.json"); const manifest = validManifest(); manifest.assets = 42; await writeFile(path, JSON.stringify(manifest)); assert.equal(await main([path, "--check-files", "--project-root", root]), 1); });
